services:
  - name: chat-world-server
    type: web
    runtime: node
    repo: https://github.com/meeighteen/chat-world-server
    branch: main
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3001
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
